find_package(fmt 11.0.2 CONFIG REQUIRED)
find_package(spdlog 1.15.0 CONFIG REQUIRED)
find_package(OpenSSL 3.3.2 CONFIG REQUIRED)
find_package(libpqxx 7.9.2 CONFIG REQUIRED)
find_package(Boost 1.86.0 CONFIG REQUIRED)
