version: "3.9"

services:
  cppapp:
    container_name: cppapp
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VARIANT=noble
        - GCC_VER=13
        - LLVM_VER=19
        - USE_CLANG=1
    command: sleep infinity
    volumes:
      - ..:/home/workspaces/:cached
    env_file: .env
    ports:
      - "8080:8080"  # Expose app on host machine
    networks:
      - db
    depends_on:
      - mysql  # Ensure MySQL starts before the app

  mysql:
    image: mysql:8.4
    container_name: db_container
    env_file: .env
    restart: always
    ports:
      - "3306:3306"    # Map MySQL port to host
    volumes:
      - db_data:/var/lib/mysql # Persist database data on the host
    networks:
      - db

volumes:
  db_data:

networks:
  db:
    driver: bridge 