version: "3.9"

services:
  cppapp:
    container_name: cppapp
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VARIANT=jammy
        - GCC_VER=13
        - LLVM_VER=18
        - USE_CLANG=1
    command: sleep infinity
    volumes:
      - ..:/home/workspaces/:cached

  redis:
    image: redis:latest
    container_name: redis_container
    env_file: .env
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data 
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "$REDIS_PASSWORD", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped
    tty: true
    stdin_open: true
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M

volumes:
  redis_data: